### ISSUE TITLE
Can you give me a setup tutorial?

### ISSUE THREAD

**Issue by mucstudio** [osamaify/pixabot#1]
Can you give me a setup tutorial?

**Comment by osamamragab** [comment]
Clone the repo
```bash
git clone https://github.com/osamaify/pixabot
cd pixabot
```
install dependencies
```bash
npm install # or yarn
```

Create .env file and add your tokens and API keys (as described in [.env.example](https://github.com/osamaify/pixabot/blob/main/.env.example))

Run on production
```bash
npm run build
npm start
```
Run on development
```bash
npm run dev
```
